// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPxxi1R2erACFbtNMD_JKr13ftKiymrKg',
    appId: '1:758403612814:web:5e7e385bba4044917c49df',
    messagingSenderId: '758403612814',
    projectId: 'main10app-1c326',
    authDomain: 'main10app-1c326.firebaseapp.com',
    storageBucket: 'main10app-1c326.firebasestorage.app',
    measurementId: 'G-JZ7JJ380VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2D6fhN4UscnEl3aPh8-y_M2rubR6shcQ',
    appId: '1:758403612814:android:67aa455b150ac5127c49df',
    messagingSenderId: '758403612814',
    projectId: 'main10app-1c326',
    storageBucket: 'main10app-1c326.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8LziX1n65c93n7tfI_3YzUEb_tWVTzUk',
    appId: '1:758403612814:ios:ba22010e6eaa3a6d7c49df',
    messagingSenderId: '758403612814',
    projectId: 'main10app-1c326',
    storageBucket: 'main10app-1c326.firebasestorage.app',
    iosBundleId: 'com.example.main10app',
  );
}
