import 'package:cloud_firestore/cloud_firestore.dart';
import '../../models/organization.dart';
import '../../services/auth_service.dart';
import '../../services/organization_service.dart';

/// Script logic to create a new organization and a default admin user
class OrganizationSetup {
  final OrganizationService _orgService;
  final AuthService _authService;

  OrganizationSetup({
    required OrganizationService orgService,
    required AuthService authService,
  })  : _orgService = orgService,
        _authService = authService;

  Future<void> createOrganizationAndAdmin({
    required String orgName,
    required String orgDescription,
    required String adminEmail,
    required String adminPassword,
    required String adminName,
    required String adminPhone,
  }) async {
    try {
      print("🚀 Starting organization setup...");

      // 1. Create User in Auth (and sign in)
      print("👤 Creating admin user: $adminEmail");
      // Use signUp to create user AND sign in to the main app instance
      // This ensures request.auth is populated for subsequent Firestore writes
      final user = await _authService.signUp(adminEmail, adminPassword);
      
      if (user == null) {
        throw Exception("Failed to create user in Authentication");
      }
      print("✅ Admin user created in Auth");

      // 2. Create Organization
      print("📦 Creating organization: $orgName");
      final newOrg = Organization(
        id: '', // Will be generated by Firestore
        name: orgName,
        description: orgDescription,
        createdAt: DateTime.now(),
        isActive: true,
      );

      // Now we are signed in, so we can write to organizations collection
      final String orgId = await _orgService.createOrganization(newOrg);
      print("✅ Organization created with ID: $orgId");

      // 3. Create Admin User Profile
      print("👤 Creating admin profile...");
      // We cannot use AuthService.createUser because it creates a new Auth user (duplicate)
      // We need to write to Firestore directly.
      // Since we are creating our own profile (user.uid), rules allow this.
      
      await FirebaseFirestore.instance.collection('users').doc(user.uid).set({
        'email': adminEmail,
        'displayName': adminName,
        'role': 'admin',
        'phoneNumber': adminPhone,
        'organizationId': orgId,
        'createdAt': FieldValue.serverTimestamp(),
      });
      print("✅ Admin profile created successfully");

      print("🎉 Organization setup completed!");
    } catch (e) {
      print("❌ Organization setup failed: $e");
      // If we created a user but failed later, we might want to clean up (delete user)
      // But for simplicity in this script, we just rethrow.
      rethrow;
    }
  }
}
